resume_from_checkpoint_path: null 
result_path: "./medical_docvu_with_assesments"
pretrained_model_name_or_path: "naver-clova-ix/donut-base"
dataset_name_or_paths: ["./donut_format"] # should be prepared from https://www.cs.cmu.edu/~aharley/rvl-cdip/
sort_json_key: False
train_batch_sizes: [1]
val_batch_sizes: [2]
input_size: [1280, 960]
max_length: 1024
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 2e-5
warmup_steps: 1
num_training_samples_per_epoch: 8000
max_epochs: 100
max_steps: 16000
num_workers: 16
val_check_interval: 1.0
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
verbose: True